version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev-db
    networks:
      - localdevnetwork
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test-db
    networks:
      - localdevnetwork
networks:
  localdevnetwork:
